name: Build and Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install .NET Framework 4.5 Developer Pack
      run: choco install netfx-4.5.2-devpack -y

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x' # specify the .NET version you need

    - name: Build with dotnet
      run: dotnet build --configuration Release EldewritoTickrateChanger.sln

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.sha }}
        release_name: Release ${{ github.sha }}
        draft: false
        prerelease: false

    - name: Upload Build Artifact to GitHub Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./EldewritoTickrateChanger/bin/x64/Release/Halo3Tickrate-ifier.exe
        asset_name: Halo3Tickrate-ifier.exe
        asset_content_type: application/octet-stream
